# Generated by Django 5.0.6 on 2024-07-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_book_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooks',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
